apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-redis-master
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/component: redis-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/component: redis-master
    spec:
      containers:
      - name: redis-container
        image: redis:5.0.6
