apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app.kubernetes.io/name: guestbook
spec:
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: redis-master
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP
