apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-frontend
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: php-container
        image: your-docker-username/guestbookphp
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: guestbook-redis-master
        - name: REDIS_SLAVE_SERVICE_HOST
          value: guestbook-redis-master
