apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  labels:
    app.kubernetes.io/name: guestbook
spec:
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
  ports:
  - name: http-port
    port: 8080
    protocol: TCP
    targetPort: 80
  type: ClusterIP
